---
name: ClangFormat Check suggestions

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["ClangFormat Check"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      (github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success')  || 
      (github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure')
    permissions:
      # contents: read
      # checks: write
      issues: write
      # pull-requests: write
      pull-requests: read
    steps:
      # - uses: GitHubSecurityLab/actions-permissions/monitor@main
      #   with:
      #     config: ${{ vars.PERMISSIONS_CONFIG }}
      # Debug
      - name: Dump GitHub context
        continue-on-error: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Create a .git directory needed by reviewdog
        run: git init
      - uses: reviewdog/action-setup@v1
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: diff
          github-token: ${{ github.token }}
          run-id: ${{github.event.workflow_run.id }}
      - run: |
          GITHUB_ACTIONS="" \
            reviewdog \
              -name="${INPUT_TOOL_NAME:-reviewdog-suggester}" \
              -f=diff \
              -f.diff.strip=1 \
              -filter-mode=nofilter \
              -tee \
              -guess \
              -reporter="github-pr-review" < "${TMPFILE}"
        env:
          TMPFILE: diff-clang-format.patch
          INPUT_TOOL_NAME: clang-format
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CI_PULL_REQUEST:
          CI_COMMIT: ${{ github.event.workflow_run.head_sha }}
          CI_REPO_OWNER: ${{ github.event.workflow_run.repository.owner.login }}
          CI_REPO_NAME: ${{ github.event.workflow_run.repository.name }}
